#!/usr/bin/env python3
"""
BabyBear Poseidon12 round constant + MDS 생성기
================================================
파라미터:
  p = 2013265921  (BabyBear: 2^31 - 2^27 + 1)
  t = 12          (state width)
  alpha = 7       (S-box: x^7  —  gcd(7, p-1)=1 이므로 전단사)
  RF = 8          (full rounds: 4 앞 + 4 뒤)
  RP = 22         (partial rounds)

Round constants: SHA-256 domain separation (nothing-up-my-sleeve)
MDS matrix     : Cauchy 구성 → 임의 부분행렬 모두 가역 → 항상 MDS

사용법:
  python3 gen_poseidon_constants.py            # poseidon_constants.h 생성
  python3 gen_poseidon_constants.py out.h      # 파일명 지정
"""

import hashlib
import sys

P     = 2013265921   # BabyBear
T     = 12
ALPHA = 7
RF    = 8
RP    = 22
TOTAL_ROUNDS = RF + RP        # 30
TOTAL_RC     = TOTAL_ROUNDS * T  # 360


# ── 보조 함수 ──────────────────────────────────────────────────────────────

def mod_inv(a, p):
    """페르마 소정리: a^(p-2) mod p"""
    return pow(a, p - 2, p)


# ── Round constants (SHA-256 seed) ─────────────────────────────────────────

def generate_round_constants():
    """
    고정 도메인 문자열로 SHA-256을 반복해 TOTAL_RC 개의 필드 원소 생성.
    값은 결정론적 & 재현 가능. 도메인 바꾸면 다른 상수가 나옴.
    """
    domain = b"Poseidon_BabyBear_p2013265921_t12_a7_RF8_RP22_RC_v1"
    constants = []
    idx = 0
    while len(constants) < TOTAL_RC:
        digest = hashlib.sha256(domain + idx.to_bytes(4, "little")).digest()
        for i in range(0, 32, 4):
            val = int.from_bytes(digest[i : i + 4], "little") % P
            constants.append(val)
            if len(constants) >= TOTAL_RC:
                break
        idx += 1
    return constants[:TOTAL_RC]


# ── MDS matrix (Cauchy) ────────────────────────────────────────────────────

def generate_mds_cauchy():
    """
    Cauchy MDS: M[i][j] = 1 / (x[i] - y[j])  mod p
    x = [0 .. T-1],  y = [T .. 2T-1]  (모두 서로 다름)
    → 모든 정방 부분행렬이 가역  → MDS 조건 자동 만족
    """
    x = list(range(T))
    y = list(range(T, 2 * T))
    mds = []
    for i in range(T):
        row = []
        for j in range(T):
            diff = (x[i] - y[j]) % P
            row.append(mod_inv(diff, P))
        mds.append(row)
    return mds


def verify_mds(mds, p):
    """가우스 소거로 행렬식 != 0 확인"""
    n = len(mds)
    m = [row[:] for row in mds]
    det = 1
    for col in range(n):
        pivot = next((r for r in range(col, n) if m[r][col] != 0), -1)
        if pivot == -1:
            return False
        if pivot != col:
            m[col], m[pivot] = m[pivot], m[col]
            det = (p - det) % p
        inv_p = mod_inv(m[col][col], p)
        det = det * m[col][col] % p
        for row in range(col + 1, n):
            factor = m[row][col] * inv_p % p
            for k in range(col, n):
                m[row][k] = (m[row][k] - factor * m[col][k]) % p
    return det != 0


# ── C 헤더 출력 ────────────────────────────────────────────────────────────

def write_header(rc, mds, out):
    mds_flat = [mds[i][j] for i in range(T) for j in range(T)]

    out.write(
        "// AUTO-GENERATED by gen_poseidon_constants.py — do not edit\n"
        "// BabyBear Poseidon12: p=2013265921, t=12, alpha=7, RF=8, RP22\n"
        "// MDS : Cauchy matrix  x=[0..11]  y=[12..23]\n"
        "// RC  : SHA-256 domain = Poseidon_BabyBear_p2013265921_t12_a7_RF8_RP22_RC_v1\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
    )

    out.write(f"// {TOTAL_ROUNDS} rounds × {T} = {TOTAL_RC} constants\n")
    out.write(f"static const uint64_t POSEIDON_RC[{TOTAL_RC}] = {{\n")
    for i, v in enumerate(rc):
        if i % T == 0:
            out.write(f"    // round {i // T}\n    ")
        out.write(f"{v}ULL")
        if i < TOTAL_RC - 1:
            out.write(", ")
        if i % T == T - 1:
            out.write("\n")
    out.write("};\n\n")

    out.write(f"// MDS [{T}×{T}] row-major — Cauchy construction\n")
    out.write(f"static const uint64_t POSEIDON_MDS[{T * T}] = {{\n")
    for i, v in enumerate(mds_flat):
        if i % T == 0:
            out.write(f"    // row {i // T}\n    ")
        out.write(f"{v}ULL")
        if i < T * T - 1:
            out.write(", ")
        if i % T == T - 1:
            out.write("\n")
    out.write("};\n")


# ── main ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    rc  = generate_round_constants()
    mds = generate_mds_cauchy()

    ok = verify_mds(mds, P)
    print(f"MDS invertible: {'OK' if ok else 'FAIL'}")
    assert ok, "MDS 행렬이 가역이 아님"

    out_path = sys.argv[1] if len(sys.argv) > 1 else "poseidon_constants.h"
    with open(out_path, "w") as f:
        write_header(rc, mds, f)

    print(f"Written : {out_path}")
    print(f"  RC    : {len(rc)} values  (first={rc[0]})")
    print(f"  MDS   : {T*T} values  (M[0][0]={mds[0][0]})")
