/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "simple_poseidon.h"

bool_t
xdr_field_element (XDR *xdrs, field_element *objp)
{
	register int32_t *buf;

	 if (!xdr_u_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CompressInput (XDR *xdrs, CompressInput *objp)
{
	register int32_t *buf;

	 if (!xdr_field_element (xdrs, &objp->left))
		 return FALSE;
	 if (!xdr_field_element (xdrs, &objp->right))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CompressResult (XDR *xdrs, CompressResult *objp)
{
	register int32_t *buf;

	 if (!xdr_field_element (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
