/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "simple_poseidon.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
poseidon_compress_1(CompressInput *argp, CompressResult *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, poseidon_compress,
		(xdrproc_t) xdr_CompressInput, (caddr_t) argp,
		(xdrproc_t) xdr_CompressResult, (caddr_t) clnt_res,
		TIMEOUT));
}
