/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIMPLE_POSEIDON_H_RPCGEN
#define _SIMPLE_POSEIDON_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


typedef u_quad_t field_element;

struct CompressInput {
	field_element left;
	field_element right;
};
typedef struct CompressInput CompressInput;

struct CompressResult {
	field_element result;
};
typedef struct CompressResult CompressResult;

#define SIMPLE_POSEIDON_PROG 0x20001235
#define SIMPLE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define poseidon_compress 1
extern  enum clnt_stat poseidon_compress_1(CompressInput *, CompressResult *, CLIENT *);
extern  bool_t poseidon_compress_1_svc(CompressInput *, CompressResult *, struct svc_req *);
extern int simple_poseidon_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define poseidon_compress 1
extern  enum clnt_stat poseidon_compress_1();
extern  bool_t poseidon_compress_1_svc();
extern int simple_poseidon_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_field_element (XDR *, field_element*);
extern  bool_t xdr_CompressInput (XDR *, CompressInput*);
extern  bool_t xdr_CompressResult (XDR *, CompressResult*);

#else /* K&R C */
extern bool_t xdr_field_element ();
extern bool_t xdr_CompressInput ();
extern bool_t xdr_CompressResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SIMPLE_POSEIDON_H_RPCGEN */
