/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simple_poseidon.h"


void
simple_poseidon_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	CompressResult result_1;
	CompressInput  poseidon_compress_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMPLE_POSEIDON_PROG, SIMPLE_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = poseidon_compress_1(&poseidon_compress_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	simple_poseidon_prog_1 (host);
exit (0);
}
