/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FRI_RPC_H_RPCGEN
#define _FRI_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef u_quad_t field_element;
#define MAX_COEFFS 1048576

struct PolyInput {
	u_int log_n;
	struct {
		u_int coeffs_len;
		field_element *coeffs_val;
	} coeffs;
};
typedef struct PolyInput PolyInput;

struct FriResult {
	field_element root;
};
typedef struct FriResult FriResult;

#define FRI_RPC_PROG 0x20001234
#define FRI_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define compute_fri_root 1
extern  FriResult * compute_fri_root_1(PolyInput *, CLIENT *);
extern  FriResult * compute_fri_root_1_svc(PolyInput *, struct svc_req *);
extern int fri_rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define compute_fri_root 1
extern  FriResult * compute_fri_root_1();
extern  FriResult * compute_fri_root_1_svc();
extern int fri_rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_field_element (XDR *, field_element*);
extern  bool_t xdr_PolyInput (XDR *, PolyInput*);
extern  bool_t xdr_FriResult (XDR *, FriResult*);

#else /* K&R C */
extern bool_t xdr_field_element ();
extern bool_t xdr_PolyInput ();
extern bool_t xdr_FriResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FRI_RPC_H_RPCGEN */
