/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "fri_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

FriResult *
compute_fri_root_1(PolyInput *argp, CLIENT *clnt)
{
	static FriResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, compute_fri_root,
		(xdrproc_t) xdr_PolyInput, (caddr_t) argp,
		(xdrproc_t) xdr_FriResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
