/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fri_rpc.h"

bool_t
xdr_field_element (XDR *xdrs, field_element *objp)
{
	register int32_t *buf;

	 if (!xdr_u_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PolyInput (XDR *xdrs, PolyInput *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->log_n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->coeffs.coeffs_val, (u_int *) &objp->coeffs.coeffs_len, MAX_COEFFS,
		sizeof (field_element), (xdrproc_t) xdr_field_element))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FriResult (XDR *xdrs, FriResult *objp)
{
	register int32_t *buf;

	 if (!xdr_field_element (xdrs, &objp->root))
		 return FALSE;
	return TRUE;
}
